Add air conditioning task, fixes #3127
streetcomplete/StreetComplete pull request #3641
Opened 2022-01-15 18:12 UTC by coolultra1

Really just the implementation of issue #3127. Still needs an icon and the elementFilter might be adjusted.

2022-01-15 18:18 UTC, matkoniecz commented
I think that either `isDeleteElementEnabled` or `isReplaceShopEnabled` is worth enabling. Though I need to test which one would fit better.

2022-01-15 18:27 UTC, matkoniecz commented
And congratulations on submitting a new quest!

2022-01-15 18:53 UTC, matkoniecz commented
![screen01](https://user-images.githubusercontent.com/899988/149634347-2ce2bff1-2859-492d-970d-07076314b2e6.png)

2022-01-15 18:56 UTC, matkoniecz approved these changes

2022-01-15 19:20 UTC, FloEdelmann approved these changes
Really cool! (Sorry, pun intended :wink:)

@coolultra1 Just a mini request: Please see https://github.com/streetcomplete/StreetComplete/discussions/2917 and update the PR description accordingly.

2022-01-15 19:25 UTC, coolultra1 commented
@FloEdelmann Thanks for telling me, I didn't know this GitHub feature.

2022-01-16 20:48 UTC, westnordost commented
Nice work! Though please make the quest only available at all in countries that are hot enough that ACs are found. E.g. it doesn't make sense in Sweden. 

I propose to only show it in countries/states that have some red, orange, yellow or green. I.e. Tropical, Subtropical and Dry 
<a href="https://en.wikipedia.org/wiki/Trewartha_climate_classification#/media/File:Trewartha_climate_classification_world_map.png">
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Trewartha_climate_classification_world_map.png/1024px-Trewartha_climate_classification_world_map.png"/></a>

You can use this tool to get all the country / state codes by clicking on them.
Given that temperate/cold climate is somewhat of a rarity on this planet, maybe it is shorter to have a list of countries where it is **not** shown.

2022-01-16 20:48 UTC, westnordost commented
This tool: https://ent8r.github.io/blacklistr/

2022-01-16 21:01 UTC, westnordost commented
I guess it would be more precise to base this on the average summer temperature, but I couldn't find such a map.

2022-01-16 21:07 UTC, westnordost commented
Maybe http://www.mappedplanet.com/tuebersicht_en.php?subthema=Temperature

2022-01-16 21:14 UTC, matkoniecz commented
> I propose to only show it in countries/states that have considerate red, orange, yellow or green

Poland has plenty of air conditioned places and is blue on this map.

This is enabled manually, so I think this is sufficient. In fact, in could be nicely used when someone spots air conditioned place quite far toward Noth - they enable quest, tag it, disable.

> average summer temperature

peaks are likely more relevant

2022-01-16 21:15 UTC, matkoniecz commented
And search `Finland air conditioning` reveals that also there you can find air conditioned places. I think that it is good without such change.

2022-01-16 22:17 UTC, westnordost commented
Okay, but then please use ...

2022-01-16 22:18 UTC, westnordost requested changes

2022-01-16 22:18 UTC, westnordost commented on app/src/main/java/de/westnordost/streetcomplete/quests/air_conditioning/AddAirConditioning.kt
> +    override val defaultDisabledMessage = R.string.default_disabled_msg_go_inside
```suggestion
    override val defaultDisabledMessage = R.string.default_disabled_msg_go_inside_regional_warning
```

2022-01-16 23:01 UTC, coolultra1 commented
@westnordost Good compromise, got it commited.

2022-01-16 23:29 UTC, westnordost approved these changes

2022-01-17 00:01 UTC, smichel17 commented
What about something more like this (very rough sketch):

![image](https://user-images.githubusercontent.com/6563664/149683358-4365a0ff-2c34-46c5-99f7-dfe69767580a.png) Or more likely in blue: ![image](https://user-images.githubusercontent.com/6563664/149683453-4d2bba0f-0001-4802-bd22-16c9e4f4b9b8.png)

Inspired by https://duckduckgo.com/?q=air+conditioning+icon&t=ffab&iar=images&iax=images&ia=images

I'm just thinking, the snowflake works, but it's a pretty generic icon to "burn" on this quest. Are there any snow related quests that we might want to use it for in the future?

2022-01-17 00:08 UTC, westnordost commented
If there are any in the future, the icon can be changed then.

2022-01-17 09:54 UTC, coolultra1 commented
@smichel17 I too think, the snowflake is ok. Your sketch: 1) puts focus to
the waves, which themselves don't really mean anything and 2) looks
complicated, making it hard to parse in an area with very many quest
bubbles.

smichel17 ***@***.***> schrieb am Mo., 17. Jan. 2022, 01:01:

> What about something more like this (very rough sketch):
>
> [image: image]
> <https://user-images.githubusercontent.com/6563664/149683358-4365a0ff-2c34-46c5-99f7-dfe69767580a.png>
> Or more likely in blue: [image: image]
> <https://user-images.githubusercontent.com/6563664/149683453-4d2bba0f-0001-4802-bd22-16c9e4f4b9b8.png>
>
> Inspired by
> https://duckduckgo.com/?q=air+conditioning+icon&t=ffab&iar=images&iax=images&ia=images
>
> I'm just thinking, the snowflake works, but it's a pretty generic icon to
> "burn" on this quest. Are there any snow related quests that we might want
> to use it for in the future?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/streetcomplete/StreetComplete/pull/3641#issuecomment-1013983133>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASRI7CB7FTLFMRHKV3DAM3TUWNL6FANCNFSM5MBIFIGA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-18 11:59 UTC, merged

2022-01-18 18:48 UTC, mcliquid commented
Can't an air conditioner also be used for heating? At least when I think of hotels or vacation apartments, this is also possible there with a normal air conditioner. This information should also be considered in the quest or not?

2022-01-18 18:57 UTC, matkoniecz commented
This quests asks about air conditioning and is not asking about heating.

If asking about heating would make sense, and passes quest guidelines ( https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete ) you can open a new issue for a heating quest.

2022-01-18 19:42 UTC, jens1o commented
Another question: Why is this quest not enabled for e.g. libraries and cinemas?

2022-01-18 20:04 UTC, matkoniecz commented
It is enabled for libraries: https://github.com/streetcomplete/StreetComplete/pull/3641/files#diff-e087c854c1df8561fd0d667718ab0e8e6873114c507c396c7f5c23c020f92f73R16

For cinemas... No idea, feel free to open a PR adding more items where it makes sense or open a new issue for that.

2022-01-22 11:40 UTC, coolultra1 commented
@mcliquid In my experience, heating is way more common than AC: Where it gets cold enough (basically everywhere that's not like the sun directly), there is heating. They don't want you to freeze but would rather have you burn, apparently.