buildings type selection in one list
streetcomplete/StreetComplete pull request #4215
Opened 2022-07-15 11:08 UTC by matkoniecz

fixes #3387 

Current: list with top answers and blue "show more" button. Pressing button replaces top values with a full list.

This: list with top values and full list below - accessible by scrolling, not by pressing button.

Seems clearly better to me (multiple people in testing tried to scroll and completely failed to notice big blue button). I also tested it by myself and it is much, much better.

Main negative is that I am not entirely happy about how I solved problem of selecting answer in the list where marked answer should be what is in category, not one of top answers before categories.

Maybe there is a smarter way to implement this? Maybe I should write own equivalent of RecyclerView?

2022-07-15 15:58 UTC, matkoniecz commented
Switching `indexOf` to `lastIndexOf` and adding `.reversed()` in getter, so that internal RecyclerView will work as expected (select item in the category, not the one in top entries) seems a bit ugly to me

> If you open a category, will the favourite answers be collapsed 

no, as it is not in category

I tried putting it into category, but category header wastes space of one entry without benefit, so I rewrote it

> If not, wouldn't that make sense

I think no - at least I sometimes get back to top answers, it would add more jumping/disappearing.

And putting it into category waste screen space

2022-07-15 16:45 UTC, westnordost commented
> Switching indexOf to lastIndexOf and adding .reversed() in getter, so that internal RecyclerView will work as expected (select item in the category, not the one in top entries) seems a bit ugly to me

And why do you have to do that?

2022-07-15 16:54 UTC, matkoniecz commented
without reversing listing following happens:

- user skips entry in top selections
- opens group
- select one of entries there, entry which was appearing also in top selection

Now the first entry (in top items) is selected instead, group which was opened closes

This is confusing and not desirable.

2022-07-15 21:43 UTC, westnordost commented
I see. Well, refactoring to make the `selectedIndex` the variable and `selectedItem` the computed property should do the trick, I think. Please try that, because currently it is indeed very hacky.

2022-07-31 08:22 UTC, matkoniecz commented
@westnordost 

Do you know or why https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/view/image_select/GroupedImageSelectAdapter.kt#L66 exists? It appears to be copying (saving?) variable and shadowing it. What is the point of that?

2022-07-31 18:35 UTC, westnordost commented
Try removing that line and you'll know.

2022-07-31 20:49 UTC, matkoniecz commented
Removing it resulted in need to add an extra `!!` in one place where Kotlin was not smart enough. And no bad effects that I noticed so I was curious whether I am overlooking something.

Either way I tried raw index numbers as primary way of identifying items and it was not working well as retracting/expanding groups was invalidating them.

I ended simply remembering group of item - now it works well in all cases without any weird behaviour or hacks in code.

I still would appreciate review but now I am happy enough to merge it.

2022-07-31 21:53 UTC, westnordost commented
> Removing it resulted in need to add an extra !! in one place where Kotlin was not smart enough. And no bad effects that I noticed so I was curious whether I am overlooking something.

Ehm, but the IDE explains why the `!!` is needed. And that should be reason enough to not use it there. If we just sticked `!!` everywhere, we might as well not have null safety.

2022-08-03 18:03 UTC, westnordost requested changes
Looks good, except for the `!!`s. You tested this?

2022-08-03 18:03 UTC, westnordost commented on app/src/main/java/de/westnordost/streetcomplete/view/image_select/GroupedImageSelectAdapter.kt
> +        holder.isSelected = selectedItem?.let { _items.lastIndexOf(it) == position } == true
There is still `lastIndexOf` here. Shouldn't it be

```suggestion
        holder.isSelected = selectedIndex() ==position
```

now?

2022-08-03 18:03 UTC, westnordost commented on app/src/main/java/de/westnordost/streetcomplete/view/image_select/GroupedImageSelectAdapter.kt
> +            if (selectedItem!!.isGroup) {
Please get rid of the !! here.

2022-08-03 18:06 UTC, matkoniecz commented
> You tested this?

Yes, definitely (after my initial idea had unexpected weird behaviour, hack had also weird behaviour just in rare case and index based solution was crashing in many cases I definitely tested also this, and to some surprise it actually worked once I fixed some mistakes, without bugs in the design itself :) )

2022-08-03 21:32 UTC, westnordost commented on app/src/main/java/de/westnordost/streetcomplete/view/image_select/GroupedImageSelectAdapter.kt
> +        val copyOfSelectedItem = selectedItem
"Copy" may be misleading, because it is not a copy. It points to the same object in memory.

2022-08-04 07:11 UTC, matkoniecz commented
@westnordost 

I marked it as a draft, as I discovered a bug that I have not spotted before, then discovered that it is present in the original code but is not triggered.

It appears that something goes wrong when list is long and one entry is retracted and another expanded. Sometimes newly expanded group is not actually shown.

For example, on `master` with addition of few more groups to make list longer ( https://github.com/matkoniecz/Zazolc/commit/bcb426eabc0394f08081975c92f8a74d580f8f85 ) following can be observed:

[device-2022-08-04-091017.webm](https://user-images.githubusercontent.com/899988/182785893-f9488e7c-f418-4e80-b397-6dc1b74fb08e.webm)

For now I remain confused what is going on. Initially I tried to understand what I broke, but as it is present also in original code (but not triggered!) so it is going a bit trickier to fix and I will need to learn more about internals of what this code is using.

2022-08-04 13:36 UTC, westnordost commented
No idea what may cause this from the top of my head. Maybe even the internal logic of the adapter is just fine and it is an issue with the RecyclerView that needs a workaround - after all, scrolling is purely UI feature.

2022-08-23 18:14 UTC, westnordost commented
The code for scrolling to ...  is here:

https://github.com/streetcomplete/StreetComplete/blob/941c75cf7cb27c9a7855adcc99d1fdd66ea89f3d/app/src/main/java/de/westnordost/streetcomplete/quests/AGroupedImageListQuestForm.kt#L89

2022-09-01 17:09 UTC, merged