Show steps dashes in overlays
streetcomplete/StreetComplete pull request #4972
Opened 2023-04-25 12:26 UTC by Helium314

Currently highlighted steps use the same style as other ways. This is confusing, as it's not immediately clear that they are steps.
With these changes, step dashes show up using outline color.
(the map style changes should also go to the mapstyle repo, but this makes things awkward for anyone wanting to test this PR)

2023-04-25 16:13 UTC, westnordost requested changes
This code doesn't belong into the `StyleableOverlayMapComponent` though but it is up to the individual overlays to define how to style the data.

2023-04-25 17:30 UTC, Helium314 commented
You could say the same for width

2023-04-25 18:25 UTC, westnordost commented
I guess you could...

To my defense, I found that since tapping on a way should feel like that way as it is shown in the background map is just selected, it should always have the same width as the way on the map. I.e. if you select a motorway, it would not match the user expectation if the highlighted line is the same width as the highlighted line would be on a footway (doesn't cover the motorway from the background map).

In contrast, whether the highlighted line is dashed or not is already a property that is defined in the `StrokeStyle` (as opposed to the width of the stroke, which is not present there because it is determined automatically). Hence, since whether the stroke is dashed or not is defined by the individual overlay, the user expectation is that the dashed-ness carries a certain meaning, e.g. that a cycle lane is only an advisory cycle lane. It would be confusing if any steps would have a dashed styling regardless.

2023-04-25 18:29 UTC, westnordost commented
However, in line 84+ (when left/right is specified but not the center stroke, the overlay mimics drawing the stroke as if it was invisible (because actually making it invisible doesn't work properly). So in this case, making the steps look like steps would make sense even with my line of argumentation. Although, no situation comes to my mind where a `highway=steps` would have a highlighting for left and right. (`StepsHandrailOverlay`? ;-) )

2023-04-26 04:19 UTC, Helium314 commented
> a way highlighted with a color should just feel like it is the same way as is shown in the backgroun

That was actually my line of thinking when I added the steps dashes

(Another thing like this is the outline dashes for private ways disappearing in overlays. I would expect them to show up the same way as on the background map)

> the user expectation is that the dashed-ness carries a certain meaning

Definitely. But the dashes introduced in this PR are
* not instead, but additional to the line (like normal steps dashes). You get `color` (line) & `strokeColor` (dashes) compared to `color` (dashes) & transparent (line) for other dashed overlay lines
* same distance as normal steps dashes, which is much shorter than dashed overlay lines

So the way simply looks like a colored version of what the user already knows as steps.
Did you try it and think it would really be confusing?

2023-04-26 11:28 UTC, westnordost commented
Huh? Then maybe I misunderstood this from reading the code. Could you post a screenshot?

2023-04-26 11:58 UTC, Helium314 commented
![steps](https://user-images.githubusercontent.com/43007630/234567570-3b4c2e92-98aa-493d-b209-7f540053caa0.png)
(the weirdly bent dashes are also visible without the overlay)

2023-04-26 12:09 UTC, westnordost commented
So how would that look like if the blue has actually a dashed stroke style? (AFAIK currently there is no overlay that uses dashed strokes for the main way.)

Anyway, regarding private ways: That would make sense because you cannot style the `StrokeStyle` to have a stroked outline.

2023-04-26 12:16 UTC, Helium314 commented
> So how would that look like if the blue has actually a dashed stroke style

Well, it's not the "normal" dashed style, but
```
    map_data-steps-dashes:
        base: lines
        blend: translucent
        dash: [0.6,0.4]
```

With the normal dashed style, the dashes are much longer.

2023-04-26 12:29 UTC, westnordost commented
Well, and they done with a shader, which is why they might look different than expected

2023-04-26 12:49 UTC, westnordost commented
If it looks something like this, it's fine

![grafik](https://user-images.githubusercontent.com/4661658/234579305-3e99ba77-bf76-4707-90b0-75f73a7c81d0.png)

If it looks something like this, it's not:

![grafik](https://user-images.githubusercontent.com/4661658/234579555-3b5ac3f2-2b0e-4416-9710-e5ff93df3d99.png)

2023-04-26 13:25 UTC, Helium314 commented
Dashes on center line look horrible in general, steps or not.
![dashes](https://user-images.githubusercontent.com/43007630/234589109-46768c09-a982-4048-9456-a1faed665575.png)

2023-04-26 13:51 UTC, westnordost commented
Hmm, this looks unexpected... I guess it is not possible to control that the outline and the stroke dashed line have the same phase and frequency...

I think it would look best if
- whether the stroke style is dashed or not never applies to the outline. The outline is always a continuous line
- since then the outline stroke style cannot be styled programmatically for each overlay, it can be styled to always follow the dashed-if-private-and-otherwise-continuous rule
- as for steps... well, I guess it could indeed be as suggested in this PR, as the steps use the outline color while the shader uses the stroke color...

2023-04-26 16:20 UTC, Helium314 commented
Should the non-dashed outlines be part of this PR?
Because currently it's not used, and it could be that by the time there is an overlay making use of it, SC has already switched to maplibre.

2023-04-26 22:21 UTC, westnordost commented
Who knows what all is possible with maplibre and what is not. I suspect many other things need to be changed too when migrating to maplibre. I think it would fit well in this PR. But I guess it doesn't **have** to be in this PR.

2023-04-27 04:33 UTC, Helium314 commented
> I think it would fit well in this PR. But I guess it doesn't have to be in this PR.

I agree that it would fit, and it would be good to have.
But I already spent more time on this than on steps dashes, and still without result. So I'd prefer to maybe give it another try later.

2023-04-27 10:56 UTC, westnordost commented
Fair enough, then this is ready to merge. I'll leave this unmerged and open until when I release the next version though, in case you find the time to work on it in the meantime.

2023-04-27 10:56 UTC, westnordost approved these changes

2023-05-01 18:49 UTC, merged

2023-05-01 19:24 UTC, Helium314 commented
Waiting really helped... I just tried again, and adding dashes for private ways just worked. Not sure what I had done wrong previously.

2023-05-01 19:35 UTC, westnordost commented
Uh, I am about to release v52.1... do you want to slip this in real quick? Then I'll wait with the release

2023-05-01 19:43 UTC, Helium314 commented
No, failed at 

> whether the stroke style is dashed or not never applies to the outline. The outline is always a continuous line

If the line has a stroke, either the stroke applies to outline too, or there is no outline at all. May need more time to fix this, as it still isn't high priority.

2023-05-01 19:54 UTC, westnordost commented
ok