Extend General fee with Sanitary Dump Stations
streetcomplete/StreetComplete pull request #5332
Opened 2023-10-25 07:30 UTC by catdogmat

This quest applies to ~50% of all sanitary dump stations on OSM. I extended the General Fee Quest, and added Sanitary Dump Stations.

2023-10-25 08:25 UTC, FloEdelmann commented on app/src/main/java/de/westnordost/streetcomplete/quests/general_fee/AddGeneralFee.kt
> +         (tourism = museum or leisure = beach_resort or tourism = gallery or tourism = caravan_site or amenity = sanitary_dump_station)
```suggestion
         tourism ~ museum|gallery|caravan_site
         or leisure = beach_resort
         or amenity = sanitary_dump_station
```

2023-10-25 20:54 UTC, catdogmat commented
I think this is ready to merge.

2023-10-26 13:12 UTC, westnordost requested changes
Hmm, but the question posed is "Do you need to pay to enter here?"

The wording doesn't really fit for sanitary dump stations. Can a wording be found that would fit all these places?

2023-10-26 18:42 UTC, catdogmat commented
How about "Is there an entrance fee or cost associated with this location?"

2023-10-26 18:44 UTC, Helium314 commented
Couldn't there just be a separate title for sanitary dump stations, or maybe generalized to places / things one does not (want to) enter?

2023-10-26 18:56 UTC, westnordost commented
Yes, that would be possible. I would also prefer such a solution. The new string could then say something like whether it costs something to use it.

2023-10-27 05:53 UTC, catdogmat commented
Ok sounds good, closing then.

2023-10-27 10:02 UTC, westnordost commented
Hu, why? I think there has been a misunderstanding. The PR is fine, but we'd need a second question text.

Notice how the `getTitle` function in line 26 has the tags as a parameter? You could check whether it is a sanitary dump station and in that case instead return a different string, something like "Do you ahve to pay ... to **use**...?"

2023-11-15 23:41 UTC, qugebert commented
@catdogmat this should work
   ```
 override fun getTitle(tags: Map<String, String>) =
        if (tags["amenity"] == "sanitary_dump_station")
            R.string.quest_generalFee_title
        else
            R.string.quest_generalFee_title2
```
and add a second title to app/src/main/res/values/strings.xml

2023-11-15 23:58 UTC, catdogmat commented
Alright, I'll add this now

2023-11-16 00:09 UTC, catdogmat commented
Thanks, @qugebert i've added it

2023-11-16 00:10 UTC, catdogmat commented
Alright, @westnordost I think this is ready for a merge!

2023-11-16 18:47 UTC, westnordost requested changes

2023-11-16 18:47 UTC, westnordost commented on app/src/main/java/de/westnordost/streetcomplete/quests/general_fee/AddGeneralFee.kt
> +         or amenity = sanitary_dump_station
```suggestion
         (
           tourism ~ museum|gallery|caravan_site
           or leisure = beach_resort
           or amenity = sanitary_dump_station
         )
```

missing brackets

2023-11-17 02:06 UTC, catdogmat commented
Ok, @westnordost I fixed the brackets

2023-11-17 19:58 UTC, westnordost approved these changes
Thanks, looks fine now!

2023-11-20 18:35 UTC, catdogmat commented
I think this is ready to merge, @westnordost

2023-11-20 18:36 UTC, catdogmat commented
Oh wait does @FloEdelmann need to review first

2023-11-21 08:43 UTC, FloEdelmann approved these changes
I'm fine with the changes, too :slightly_smiling_face:

2023-11-21 14:01 UTC, westnordost commented
It will be merged for the next main release (not for a bugfix release, which I expect the next release to be)

2023-11-26 13:27 UTC, merged