Do not ask payment methods if payment:others=no is set
streetcomplete/StreetComplete pull request #5589
Opened 2024-04-21 00:00 UTC by urbalazs

The [wiki](https://wiki.openstreetmap.org/wiki/Key:payment:*#Others) says that `payment:others=no` can be used if you have already indicated **all** methods of payment which are accepted. Do not need to ask whether cash or cards are accepted if this key is set.

2024-04-21 14:20 UTC, mnalis commented
Make sense, although one should add checks for `no` value explicitly (there are few percent of other values for `payment:others`, like `yes`)

2024-04-21 15:16 UTC, Helium314 commented
Shouldn't `yes` mean that _all_ other methods are accepted? (doesn't sound like something that could actually be correct though)

2024-04-21 19:41 UTC, westnordost requested changes
Thanks for the PR, makese sense! As per the comments above, the filter should be `payment:others != no` though.

2024-04-21 20:50 UTC, urbalazs commented
I added only the key without value because

- `payment:others=no` means that no need to ask if missing cash or card method is needed since others is **no**
- `payment:others=yes` means that no need to ask if missing cash or card method is needed since others is **yes** - I know that this makes no sense, but StreetComplete is not a validator to decide whether a tag makes sense or not
- missing `payment:others=*` means that SC should ask if missing cash or card can be accepted

2024-04-21 21:14 UTC, westnordost commented
I think `yes` is the opposite of `no`, so it means "yes, there are other payment methods that may accepted" rather than "yes, ANY other payment method imaginable is accepted". As you and Helium314 noted, the latter would make no sense.

2024-04-22 11:57 UTC, mnalis approved these changes

2024-04-22 13:04 UTC, merged