remove not only ${key}, but also source:${key}
streetcomplete/StreetComplete pull request #6067
Opened 2024-12-31 03:11 UTC by mnalis

when trimming keys in `KEYS_THAT_SHOULD_BE_REMOVED_WHEN_PLACE_IS_REPLACED`, remove not only every `$key` that matches, but also every `source:$key` and `check_date:$key` that matches too. 

Rationale being that if we are removing no longer relevant key, we should remove its metadata too (e.g. from where it initially came, and when it was last verified).

- Fixes https://github.com/streetcomplete/StreetComplete/issues/6057
- Fixes https://github.com/mnalis/StreetComplete-taginfo-categorize/issues/30

Tested with [debug apk ](https://github.com/mnalis/StreetComplete/actions/runs/12554714035) on e.g. https://www.openstreetmap.org/node/832042729 which has `source:opening_hours` and which regular SC does not remove...

2024-12-31 12:06 UTC, matkoniecz requested changes
Can you add test or two?

I would test that:

- lone source:opening_hours is removed
- when source:opening_hours and opening_hours are there both are removed

(I can also add them if you do not want, let me know in such case)

2024-12-31 12:11 UTC, westnordost commented
Hmm, what about Things, then?

I was thinking that maybe it would be a better solution if this is done for **any** edit? (I.e. if `key` is edited, `source:key` is deleted?)

2025-01-02 00:37 UTC, mnalis commented
> I was thinking that maybe it would be a better solution if this is done for any edit?

Agreed! Here is ([debug apk](https://github.com/mnalis/StreetComplete/actions/runs/12575449504) that does it that way (in `fun remove()`) if others want to try it out. I've quickly checked manually on https://www.openstreetmap.org/node/832042729 and it seems to work.

> Can you add test or two?

Good idea, will try

2025-01-03 23:59 UTC, mnalis commented
Current revision of this PR seems to be [successful](https://github.com/mnalis/StreetComplete/actions/runs/12605393625) in additionally removing `source:$key` when `$key` is removed (And added test seems to confirm it), so in its current state it would fix specific problem reported in #6057. 

---

However, I think it would be good idea to also remove `check_date:$key` and other related date keys, as those are also obsolete when `$key` is removed.

However, trying to do that breaks various tests (see `FIXME`s in this PR) as it seems to be removing `check_date:$key` in cases when instead a modification was done (so check date should be _updated_ instead of removed). 

I've been trying to look into it, but it is at boundary of my abilities. I'll give it another try after several days (going AFK now), so:
- if anyone in the meantime cares to gives me a hint or two where to look, it would be greatly appreciated. Or,
- if anyone more skilled want to take it from here instead, I'm good with that too. Or, 
- otherwise, this PR could also be merged as-is, as it fixes `source:$key` issue successfully, and fixing other related meta-keys (`check_date:$key`) and friends) can be left as an exercise for another time.

2025-01-08 22:41 UTC, westnordost commented
Did you read https://github.com/streetcomplete/StreetComplete/issues/6057#issuecomment-2571377199 ?

2025-01-09 00:36 UTC, mnalis commented
> Did you read https://github.com/streetcomplete/StreetComplete/issues/6057#issuecomment-2571377199 ?

***Now*** I did :open_mouth: :smiley: 

I've thus abandoned the idea of generic use of `tags.remove()` removing meta-prefixes like `source:`

However, I've rolled back this PR to only remove `source:x` and `check_date:x` if `x` is listed in `KEYS_THAT_SHOULD_BE_REMOVED_WHEN_PLACE_IS_REPLACED` and user has selected that that that shop/amenity no longer exists. Would that work?

2025-01-09 02:17 UTC, matkoniecz commented
I think so? While doing it in general would be potentially problematic, tagging space for shops should be smaller.

And here this tag removal on shop retagging is anyway a heuristic - quite smart and where a lot of effort went into it, but still not 100% accurate either.

2025-01-09 12:20 UTC, closed without merging

2025-01-09 12:46 UTC, mnalis commented
(ref: https://github.com/streetcomplete/StreetComplete/commit/65bba70b714a0273313c3051fe89c7f01fd5ec27)